backend:
  name: github
  repo: grod220/CCS-B.B.Warfield
  branch: master

media_folder: static/uploads

collections:   
  - label: "Site Content"
    name: "content"
    delete: false
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "home"
        file: "src/content/home.yml"
        fields:
          - label: Mission Block
            name: mission
            widget: string
            fields:
              - { name: pretext, label: 'Mission pretext', widget: string }
              - { name: mission-statement, label: 'Mission Statement', widget: string }
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Team
            name: team
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
