backend:
  name: github
  repo: grod220/CCS-B.B.Warfield
  branch: master

media_folder: static/uploads

collections:   
  - label: "Site Content"
    name: "content"
    delete: false
    editor:
      preview: false
    files:
      - label: "Homepage"
        name: "home"
        file: "src/content/home.yml"
        fields:
          - label: Mission Block
            name: mission
            widget: object
            fields:
              - { name: pretext, label: 'Mission pretext', widget: string }
              - { name: mission-statement, label: 'Mission Statement', widget: string }
          - {label: Service Times, name: service-times, widget: string}
      - label: "Homepage"
        name: "home"
        file: "src/content/home.yml"
        fields:
          - label: Mission Block
            name: mission
            widget: object
            fields:
              - { name: pretext, label: 'Mission pretext', widget: string }
              - { name: mission-statement, label: 'Mission Statement', widget: string }
          - {label: Service Times, name: service-times, widget: string}